name: Take Screenshots Hourly

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # Runs the workflow every hour

jobs:
  take-screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gconf-service \
            libasound2 \
            libatk1.0-0 \
            libatk-bridge2.0-0 \
            libcups2 \
            libdbus-1-3 \
            libexpat1 \
            libfontconfig1 \
            libgbm1 \
            libgtk-3-0 \
            libnspr4 \
            libnss3 \
            libx11-xcb1 \
            libxcomposite1 \
            libxcursor1 \
            libxi6 \
            libxrandr2 \
            libxss1 \
            libxtst6 \
            xdg-utils

      - name: Install dependencies
        run: npm install

      - name: Create screenshots directory
        run: mkdir -p foreca-clips

      - name: Run script
        run: npx ts-node take-screenshots.ts

      - name: Upload screenshots as artifact
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: foreca-clips


